### ISSUE TITLE
Completely non-functional (probably conflict)

### ISSUE THREAD

**Issue by simon-horny** [zen-mod/ZEN#563] opened 2021-03-01 00:44 UTC
**Arma 3 Version:** `2.02.147284` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable)
**ZEN Version:** `1.x.x` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- Single Player Cheat Menu
- All of the RHS mods, cup and other stuff adding things
- Zeus Cache
- ACRE
- ACE
- Real engine
- Fucton of others that probably have nothing to do with functionality of ZEN
```

**Description:**
First of all not reproducible with only ZEN and CBA. I run a fucton of mods, I know, things tend to break but I still believe it should work normally. My problem is, when I run any map, I get the error (see bellow), only couple of factions load, I can click through tabs in Zeus but I can't click on anything in them and I am unable to use the right click menu. I am 99% sure it is a mod conflict, I am just unable to tell what is causing it. If you can't be arsed to deal with mod conflicts, I get it, just close the issue and carry on. I will however try and figure out what's causing it for future reference and will try to reach out to you. 

**Expected behavior:**
Functional Zeus.

**Steps to reproduce:**
1. Run
2. Launch any map
3. Enable zeus through SPCM
4. Be unable to do anything

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Screenshots:**
![20210301013054_1](https://user-images.githubusercontent.com/47527204/109439399-6e25fe00-7a2e-11eb-82bf-133f16a541f8.jpg)

**Comment by neilzar** [comment] 2021-03-01 00:49
Same issue as #557 

Please check your other mods as you probably have a mod that has an incorrect configuration. Closing as this is not a ZEN issue.

**Closed by neilzar** 2021-03-01 00:49 UTC
Labels: bug

**Comment by simon-horny** [comment] 2021-03-01 00:51
Good, should I still hit this thread with the info what precisely caused it?

**Comment by neilzar** [comment] 2021-03-01 00:54
If you find the cause, feel free to share. Could help others that face this same issue.

**Comment by simon-horny** [comment] 2021-03-01 00:56
All right, thank you for your time.
