### ISSUE TITLE
Feature Request: Ability to command squads while using Zeus remote control

### ISSUE THREAD

**Issue by FireMagus** [zen-mod/ZEN#462] opened 2020-08-26 04:58 UTC
In the Achilles mod there was a way to take over the AI squad leader and command the other AI like you would normally (Spawn a squad, hover over squad leader and hold Left alt + 2x LMB). I would like to see it added to Zeus Enhanced if possible please.

**Comment by CreepPork** [comment] 2020-08-31 14:43
Duplicate of #54.

**Closed by CreepPork** 2020-08-31 14:43 UTC
Labels: duplicate
