### ISSUE TITLE
ZEN conflicting with other mods

### ISSUE THREAD

**Issue by Slavi-San420** [zen-mod/ZEN#582] opened 2021-04-10 15:13 UTC
**Arma 3 Version:** `2.02.147359` stable
**CBA Version:** `3.15.3` stable
**ZEN Version:** `1.10.0` stable

**Mods:**
```
- Modpack: https://pastebin.com/7FF9ijHf (includes ZEN & CBA)
```

**Description:**
ACE "disables" itself when using additional mods and ZEN. Using features such as ACE Arsenal, Loadouts made in ACE Arsenal, Zeus Interface & Modules is not possible when using the 'Mods' provided in the section above. Tried to run just ACE, CBA & ZEN and it worked fine but failed to do so if running with additional mods.

**Expected behavior:**
I expect the ACE arsenal to open, it doesn't. Expected to have loadouts loaded on the AI but they're gone. Expected to find modules in a category such as 'Fire Support' but there were just vanilla ones and none added by ZEN.

**Steps to reproduce:**

1. _Use the modpack in 'Mods' section_
2. _Load 3DEN and place an infantry_
3. _Attempt to open ACE Arsenal_
4. _Load into Self-Hosted MP, attempt to use ACE_

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Additional information:**
I did test ZEN without additional mods and it worked fine, but it conflicts with another mod regarding ACE. Also happy to provide any information regarding this, Discord: Ahri#0420 (465016746546429964)

**RPT log file:**
- https://pastebin.com/XJU3XVKh

**Screenshots:**
N/A

**Comment by neilzar** [comment] 2021-04-10 16:02
First off, you don't need Arma Zeus Cache anymore as that functionality is now implemented in the base game. As for the actual issue, it is something that has been fixed already with #565 which will be part of 1.11.0. Until then you'll have to figure out which mod causes the issue, as you are running a mod that has an incorrect config. 

Closing as it is a duplicate of #557 and has been fixed already for the next release.

**Closed by neilzar** 2021-04-10 16:02 UTC
Labels: bug
