### ISSUE TITLE
Better AI unit remote controlling / possession 

### ISSUE THREAD

**Issue by zzguy12** [zen-mod/ZEN#572] opened 2021-03-20 04:59 UTC
**Is your enhancement related to a problem?**
Yes. When remote controlling units, it uses the vanilla zeus system, whereas the zeus is controlling the ai as if it were a remote vehicle. What this means is, the zeus is not actually in full control of the character, and lacks access to more advanced user actions. For example, vehicles with custom scripts added via addaction do not appear when manned by a zeus. Specific examples of this include not being able to turn on beacons in police / emergency vehicles from vanilla or mods, custom airbrakes and thruster actions on the pelican of the OPTRE mod, advanced actions available in aircraft from the USAF mod. Really anything with non-default interactions seem to be effected.

**Solution you'd like:**
The Achilles mod has an advanced possession system, wherein holding alt and double clicking an ai unit will seemingly make that ai unit a playable unit, and then instantly team switch the zeus to be playing that character. Its worth noting that with this method, there is no scroll menu user actions stating "release UAV controls". This is the main difference between the two methods, as it allows for full control over AI in a mission. Pressing Y returns you to the zeus interface as normal.

**Alternatives you've considered:**
I have considered running Achilles alongside ZEN for this feature, but the mods are so similar that they conflict a lot and create a messy interface (even after config editing). ZEN seems superior in nearly every other aspect so I don't want to use Achilles over it.

**Comment by neilzar** [comment] 2021-03-20 17:57
Duplicate of #54

**Closed by neilzar** 2021-03-20 17:57 UTC
Labels: duplicate, enhancement
