### ISSUE TITLE
Better remote control + Task Force

### ISSUE THREAD

**Issue by Ghosto27** [zen-mod/ZEN#527] opened 2021-01-24 04:30 UTC
In Achilles was a feature, when you could use control unit and speak in TeamSpeak from unit face. 
In was achieved by Alt + Double Click. Its not simple moduleRemoteControl function, but was switchUnit func. which allow you play from another character. It was best function in Achilles that allow you to Role Play easily.

Can you integrate that function to ZEN?

You can find it from Achilles:
addons\ui_f\functions\keyEvents\fn_HandleMouseDoubleClicked.sqf
addons\functions_f_achilles\functions\selectUnit\fn_switchUnit_start.sqf

**Comment by mharis001** [comment] 2021-01-24 04:49
Closing as duplicate of #54 .

**Closed by mharis001** 2021-01-24 04:49 UTC
