### ISSUE TITLE
Hold Position/Achilles Garrison

### ISSUE THREAD

**Issue by ECloc** [zen-mod/ZEN#493] opened 2020-12-22 20:47 UTC
In Achilles, the "Garrison Group" Module could be set to 0 and therefore anchor a group of droids to their current position. 
The current Garrison Group Module does not allow for this functionality anymore, as groups that are garrisoned with no valid garrison points are unaffected. It's difficult to even find usable workarounds and most require scripting.

Therefore I propose that either a "Hold Position" Module be added or that this functionality be restored.

I and many of the other Zeuses that I've played with have used this potentially unintended functionality from Achilles to place enemies in interesting locations that would otherwise be impossible and to fully utilize custom assets as these sometimes miss garrison locations.

**Comment by TheRadiumDude** [comment] 2020-12-22 20:50
You could disable AI `Move`, which would disallow AI to move at all, through their abilities menu in attributes. Will this not solve the problem?

**Comment by mharis001** [comment] 2020-12-23 06:41
You can disable the AI's ability to `PATH` which will keep them in position. Garrison should place units in buildings and not fix them in their current position (that seems like unintended behaviour to me).

**Comment by oOKexOo** [comment] 2020-12-23 07:54
It was never unintended behavior. There are two ways to treat units that cannot be placed. Either leave them alone or fix them such that they can be manually placed. Both are valid solutions in my opinion. As already stated by others, the same behavior can already be achieved by using the disable AI feature.

**Comment by TheRadiumDude** [comment] 2020-12-23 11:51
Closing as a solution has been given.

**Closed by TheRadiumDude** 2020-12-23 11:51 UTC
