### ISSUE TITLE
Suppressive Fire (Fire Support Module)

### ISSUE THREAD

**Issue by Glxde** [zen-mod/ZEN#413] opened 2020-06-18 01:46 UTC
**Is your feature request related to a problem?**
Not related to a problem

**Solution you'd like:**
I'd like the suppressive fire module added to zen

**Alternatives you've considered:**
Tried to use zen and achillies together but its a bit buggy

**Additional context:**

**Comment by CreepPork** [comment] 2020-07-28 13:52
Duplicate of #222.

**Closed by CreepPork** 2020-07-28 13:52 UTC
Labels: duplicate
