### ISSUE TITLE
Feature request: Breachable doors

### ISSUE THREAD

**Issue by YetheSamartaka** [zen-mod/ZEN#464] opened 2020-08-31 14:49 UTC
**Is your feature request related to a problem?**
Add ability to set doors to breachable state. Currently, you can open/close doors and lock them, but there is an option to set them breachable.

**Solution you'd like:**
Similarly to what Achilles has, but you would set it in a beautiful ZEN door management module. It should support both vanilla, ace and possibly RHS explosives.

**Alternatives you've considered:**
Using ZEN and Achilles at once, which is not ideal solution or adding external scripts which are sometimes wonky.

**Additional context:**
This feature is one of the last things that holding me and many others back from switching from Achilles to ZEN.

**Comment by CreepPork** [comment] 2020-08-31 15:23
Duplicate of #43.

**Closed by CreepPork** 2020-08-31 15:23 UTC
Labels: duplicate
