### ISSUE TITLE
With new ZEN Version ACE Menu does not Work and Addon Options

### ISSUE THREAD

**Issue by 85thOperationCommand** [zen-mod/ZEN#557] opened 2021-02-20 22:02 UTC
**Arma 3 Version:** `2.0` (stable)
**CBA Version:** `3.15.2` (stable)
**ZEN Version:** `1.10.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3
- ACEX
- RHS
- USAF
- CUP
- ZEN
```

**Description:**
Hey i have problems too. 1 Problem i can fixed myself with redownload but the other found problems after 10 houres or more its you have in editor you can press "addon-options" and nothing happend if you have it on MP local server on you can see the ace and addon-options menus are not visible. for me looks like something Block ace or CBA or both. i run both on last version they give us. 2. was long time loadingscreens when connecting to Server where u can run and shooting loading screen is still there . I cant say its fact on size of modsets coz i have 3. With 1.9 no Problem on that mod. but with 1.10. i not know other have that same found like me or my unit.

**Expected behavior:**
Loading Screen Disappear, ACE menu on and addon options in editor works

**Steps to reproduce:**
Try to connect to a linux server or try to click Addon Options in the EDEN editor and the ACE menu works

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by neilzar** [comment] 2021-02-20 22:10
Can you try with just CBA and ZEN, please?

**Comment by 85thOperationCommand** [comment] 2021-02-20 22:11
Has already been tried

**Comment by mharis001** [comment] 2021-02-20 22:12
Can't reproduce even with all of the mods listed. If I understand the issue correctly, addon options are unavailable and the ACE interaction menu does not work?

**Comment by 85thOperationCommand** [comment] 2021-02-20 22:17
yes and the loading screen does not disappear when you try to connect to a Linux server but you can still shoot and run

**Comment by 85thOperationCommand** [comment] 2021-02-20 22:22
here are logs from the server https://pastebin.com/sP12Jwt4

**Comment by neilzar** [comment] 2021-02-20 22:55
The second RPT logs show ZEN 1.9, not 1.10.

**Comment by neilzar** [comment] 2021-02-20 23:21
There are no errors in the server log that I can directly attribute to ZEN. There are some errors related to CBA. The first being an error in using a keybind function. After that there is an error where it is expecting a string but gets a number, checking the CBA code that happens when it is looking at all the units defined in a CfgPatches entry; so somehow one of your mods is defining a unit as a number rather than a string. The final error I am not sure what is causing it, but likely the error before that.

**Comment by 85thOperationCommand** [comment] 2021-02-21 23:42
Here are RPT Logs with 1.10 mods and Ace Compat for ZEN loaded. I also have a screenshot where the addon options are missing
![zen10](https://user-images.githubusercontent.com/37073363/108642645-dd3ba980-74a6-11eb-9135-3ac55c40eb14.jpg)

**Comment by mharis001** [comment] 2021-02-22 04:35
```
if (_x isKindOf "AllVehicles" && {!(_x isKindOf>
 3:16:39   Error position: <isKindOf "AllVehicles" && {!(_x isKindOf>
 3:16:39   Error iskindof: Typ Zahl, erwartet Zeichenfolge,Objekt
 3:16:39 File x\zen\addons\faction_filter\XEH_preStart.sqf..., line 12
 ```

As @neilzar said, looks like some mods incorrectly have numbers in their `CfgPatches` `units` arrays instead of all strings.

**Comment by neilzar** [comment] 2021-02-24 22:41
Closing as the issue is not proven to be caused by ZEN.

**Closed by neilzar** 2021-02-24 22:41 UTC
Labels: invalid

**Comment by Mirrowel** [comment] 2021-03-04 00:05
So having the same issue(details below), but i found the mod responsible for it. Judging by the amount of reports issues are not just with this mode, and only happened after last update. Something possibly related to buildings/maps(steam comments).
https://steamcommunity.com/sharedfiles/filedetails/?id=2244476936

What exactly breaks: Addon options in editor, Then when loaded into the mission ace interaction is impossible and zeus does not work(nothing happens on keypress). Ace compat enabled or not does not matter.
Error i get on mission start is included below. I do not get it without the linked mod
![image](https://user-images.githubusercontent.com/28632877/109888565-b9414a80-7c94-11eb-827c-b34db4e9f3a5.png)

**Comment by 85thOperationCommand** [comment] 2021-03-04 04:24
Hi thank you for the information. Australia map is also not working With zen 1.10--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04/03/2021, 01:05 schrieb Mirrowel <notifications@github.com>:

   
  So having the same issue(details below), but i found the mod responsible for it. Judging by the amount of reports issues are not just with this mode, and only happened after last update. Something possibly related to buildings/maps(steam comments). https://steamcommunity.com/sharedfiles/filedetails/?id=2244476936 
  What exactly breaks: Addon options in editor, Then when loaded into the mission ace interaction is impossible and zeus does not work(nothing happens on keypress). Ace compat enabled or not does not matter. Error i get on mission start is included below. I do not get it without the linked mod
