### ISSUE TITLE
Feature Request - Limit the factions available to a Zeus

### ISSUE THREAD

**Issue by PraetorianPants** [zen-mod/ZEN#485] opened 2020-11-03 10:56 UTC
In Achilles, there was a very useful setting option that allowed you to restrict the factions available to Zeus. So depending on the missions or deployments you could cut out the factions in OPFOR, BLUFOR etc that you were not using. There is limited space otherwise on the menu bar making it hard to find your units.

**Comment by CreepPork** [comment] 2020-11-16 20:45
Duplicate of #142.

**Closed by CreepPork** 2020-11-16 20:45 UTC
Labels: duplicate
