### ISSUE TITLE
Deep Copy/Paste not working

### ISSUE THREAD

**Issue by Tazerfingers** [zen-mod/ZEN#429] opened 2020-07-08 06:44 UTC
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
-CUP Weapons, Units, & Vehicles
-Burnem
-BlastCore
-Ares
-Unsung
-Bloodlust
```

**Description:**
When trying to use the Deep Copy/Paste function, It only makes an action failed noise, like trying to spawn something without enough resources in zeus for example. I've tried to rebind and reassign the action but it always leads to the same outcome.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
personal server rented from host

**Additional information:**
A possibility is that the map or mod files cannot be deep copied, but it also doesn't work with base game content. I am on Tanoa playing with the Cup weapons and Unsung weapons.

Apologies for posting twice, I mistakenly didn't submit the first time under the bug category, Feel free to delete my first report.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by mharis001** [comment] 2020-07-08 07:20
The deep copy/paste keybinds are meant to play the `RscDisplayCurator_error01` sound. Please try with CBA and ZEN only and upload the RPT.

**Comment by mharis001** [comment] 2020-07-28 01:23
Can't reproduce. Closing as issue template has not been filled out and requested information has not been provided.

**Closed by mharis001** 2020-07-28 01:23 UTC
Labels: bug
