### ISSUE TITLE
Zeus module won't open with Y when testing a mission in EDEN editor.

### ISSUE THREAD

**Issue by KevinTOC** [zen-mod/ZEN#592] opened 2021-05-24 13:35 UTC
I can't open the Zeus module with this mod. I do have other mods installed, but none of them alter the overall functionality of the Zeus module.

The error I get is `cannot execute module, error found in 'zen_modules_fnc_bi_modulecurator'` when I try to test a mission. I have the module just in my world, nothing's weird or has been changed about the module, but I just can't access Zeus when testing the mission in the EDEN editor.

**Comment by mharis001** [comment] 2021-05-24 13:56
Duplicate of #557. Will be fixed in 1.11.0.

**Closed by mharis001** 2021-05-24 13:56 UTC
Labels: duplicate
